# Generated by Django 4.2.1 on 2024-04-26 12:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('Category', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Deadline', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 18, 44, 26, 591145))),
            ],
        ),
    ]
